# Generated by Django 4.1.3 on 2022-12-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomia', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bares',
        ),
        migrations.DeleteModel(
            name='Restaurantes',
        ),
    ]
