# Generated by Django 4.1.3 on 2022-12-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomia', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bares',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restaurantes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
