# Generated by Django 4.1.3 on 2022-12-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomia', '0004_bares_imagen_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bares',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
