# Generated by Django 4.1.3 on 2022-12-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastronomia', '0005_alter_bares_imagen_alter_restaurantes_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantes',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
